### ISSUE TITLE
Bug: watch history gone after updates

### ISSUE THREAD

**Issue by SanderM2** [euzu/m3u-filter#101]
I’m using m3u-filter mainly for filtering my TV channels but recently noticed that my VOD content is barely usable when using m3u-filter.

The first problem I noticed is that when I put something in my watchlist in Tivimate it becomes something else the next day. After it updated the lists.
So for example. I put ‘show ABC’ in my watchlist and tomorrow my watchlist no longer contains ‘show ABC’ but ‘show XYZ’ instead.

Maybe this has something to do with changing ID’s?

The second problem that I have is when playing some VOD. It usually works. But when i try to pause or skip back/forward. Playing no longer works for that item, at all! I can not even restart it from the beginning. 

It just won’t play this same item anymore with errors 400 or 509 shown in Tivimate.
Only the next day. After another update, playing works again but I can repeat this issue. So if I press skip/forward/pause it stops working until it gets another update.

I can still play other items when one is failing. But the same thing happens to that item when I press pause/skip/forward… 

So I cannot pause anything…

Not sure what could be the cause. If have redirect enabled already so I have no idea what is different. It should have a direct connection to original server….

**Comment by euzu** [comment]
@SanderM2 i think this is the changing id problem. I am working on a solution.

**Comment by solohpgh** [comment]
I'd like to add that I have the same issue.

Thanks for addressing and looking into this @euzu

**Comment by euzu** [comment]
@SanderM2 and @solohpgh  I've done a lot of refactoring and new implementations to ensure that the assigned virtual_ids are properly maintained for the playlist items. A lot has changed, and I can't guarantee that everything works perfectly at this point — this is where I need your help.

I've pushed the changes to the branch [feature/virtual_id_handling](https://github.com/euzu/m3u-filter/tree/feature/virtual_id_handling).

The file data structures have changed, so you'll need to delete the `data` folder.

If you can't build your own binary, here is one:
[m3u-filter.gz](https://github.com/user-attachments/files/17560552/m3u-filter.gz)

**Comment by solohpgh** [comment]
Ok - I am trying the new build.

Though currently can't get past access to the config files:

`[2024-10-30T07:55:52Z ERROR m3u_filter] M3uFilter error: Could not find file config.yml No such file or directory (os error 2)`

I'll continue to troubleshoot myside.

**Comment by iceman73** [comment]
I can confirm this fixed my issue with my provider where Virtual ID always errored as being empty.

Also resume is working correctly

**Comment by euzu** [comment]
@iceman73  did you compile your version from the branch ?  
I did some updates on the code with optimizations.
It would be helpfull if you could test the latest feature branch version.

The file structure has changed, please delete the old data.

**Comment by iceman73** [comment]
> @iceman73 did you compile your version from the branch ? I did some updates on the code with optimizations. It would be helpfull if you could test the latest feature branch version.
> 
> The file structure has changed, please delete the old data.

Yes I compiled from this morning commit

**Comment by euzu** [comment]
@iceman73 Here is the optimized version that includes the use of buffered readers and writers, garbage collection for fragmented files, and read/write locks on I/O operations to prevent race conditions.

**Comment by solohpgh** [comment]
I’ve rebuilt using the latest…. However that has reset my testing. 

I’ll report back, staying on this version for a few days.

**Comment by euzu** [comment]
@SanderM2 , @solohpgh, @iceman73  i have created a new release with the virtual_id branch. The branch is now merged into master and not available anymore.

I am closing this issue, if any bugs appear, please create a new issue.

**Comment by iceman73** [comment]
moved to master and still working great

**Comment by euzu** [comment]
@iceman73 the master has the epg on disk processing feature to avoid excessive memory usage through loading the xml file into memory. Did you check this feature ? is the epg working as expected ?

**Comment by iceman73** [comment]
I confirmed this on one of the EPGs I used its working, I changed to using the parsed one from m3u-filter and no issues

**Comment by solohpgh** [comment]
An update from me. 

The final branch before master release has been working great and stabilised the provider changes that were not tracked by Tivimate. 

I’ll be switching to the master.
