### ISSUE TITLE
Chanel rename doesn't work on XTREAM

### ISSUE THREAD

**Issue by pypckompsite** [euzu/m3u-filter#118]
**Describe the bug**
On M3U output the filter works, when I change the output type to "XTREAM" the channels go back to their original names

**To Reproduce**
1. Open sources.yml file
2. Edit output section of selected target - change type from m3u to xtream
3. Set API, set credentials, ...
4. Look in the player, and see unchanged chanell names

**Expected behavior**
Rename working on all ouput types

**Config snippets**

      - name: All
        type: xtream
        output:
          - type: xtream
        filter: "!FilterALL!"
        rename:
          - field: group
            pattern: POLONIA
            new_name: PL
          - field: title
            pattern: "PL: (.*)"
            new_name: $1
          - field: name
            pattern: "PL: (.*)"
            new_name: $1
        processing_order: frm

**Comment by euzu** [comment]
@pypckompsite m3u-filter does not differentiate between m3u or xtream playlist.  All inputs are fetched and  merged to a unified structure. Then all processing happens. Could it be that your client has cached the names? If you confirm that this problem exists after refresh i can try your example.

**Comment by euzu** [comment]
Did you look at the log for errors?

**Comment by pypckompsite** [comment]
**KIND OF FIXED**, I rebooted the machine and it started working. Somehow renaming the channels required a reboot, while group renaming works on the fly. Sorry for wasting your time. I think its ok to mark this "Resolved"

On the original issue:
No errors in log. I tried on "fresh" STB, and the names are not changed. Curiously, Group name gets changed.
