### ISSUE TITLE
No docker image for armv8

### ISSUE THREAD

**Issue by andresjocrack** [euzu/m3u-filter#132]
There is no image that can be used in a raspberry pi 4/5, as the arm image is armv7, which only runs in older (And mostly unsupported by other images) versions of RPi. 

**To Reproduce**

Do the following in a Raspberry pi:

```
docker pull ghcr.io/euzu/m3u-filter:latest
latest: Pulling from euzu/m3u-filter
Digest: sha256:a36963b54ad99c07c59b7434fd192a2dad43ccebc8a333ed8cce40cb9aca8433
Status: Image is up to date for ghcr.io/euzu/m3u-filter:latest
ghcr.io/euzu/m3u-filter:latest

docker run -i ghcr.io/euzu/m3u-filter:latest 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec ./m3u-filter: exec format error
```

**Expected behavior**
I would like to be able to run the image in my Rpi4

**Desktop (please complete the following information):**
 - OS: Dietpi (But most likely anything running in an armv8 machine)

I would be happy to help, I manage to generate an image myself, but I am no longer able, as currently the frontend application fails to compile from my environment.

**Comment by euzu** [comment]
@andresjocrack  You can take the frontend from the latest release zip. It is javascript and does not run on the machine, it runs in the Browser.
I have created a binary,  if you can confirm that it works, i can create an image with every release.

[m3u-filter.gz](https://github.com/user-attachments/files/18041375/m3u-filter.gz)

**Comment by andresjocrack** [comment]
Thanks!,

I did not think of that possibility, but it certainly works well. A "native" armv8 version in the repository would still be ideal, but with this I managed to generate my own dockerfile so that I can generate it myself in my RPi4.

Still wondering why the generation of the frontend part fails (Both in Rpi and Mac), while it worked a couple of weeks ago... If you are interested I can share logs with you.

**Comment by euzu** [comment]
Yes why not, if it is someting with ssl then there is a fix for node.

Did the binary work?

**Comment by andresjocrack** [comment]
Hi,

Here is a commented log file with the whole process, I start with a fresh clone of the repository, and then attempt to build the node part, but it fails. This is on a Mac, but in Rpi I get the same result (Just slower!).

[node-build-error.log](https://github.com/user-attachments/files/18048007/node-build-error.log)

Regarding the binary, I did not use it, as I managed to compile it for myself, just by applying small changes in the dockerfile. What I did is creating a dockerfile that automatically pulls the code from Github and compiles the rust part. I parameterized the version and architecture, so that I can use it in multiple environments. With this, I can easily regenerate it upon each upgrade. The node construction part can be easily integrated there, by now I am downloading the web part.

Just in case you might be interested (Ignore the extension, github rejects other types of file), here it is

[Dockerfile.log](https://github.com/user-attachments/files/18048026/Dockerfile.log)

**Comment by euzu** [comment]
@andresjocrack which node version are you using? I am using node v22.9.0

**Comment by andresjocrack** [comment]
Sorry about the late reply, I did not get a notification.

This dockerfile is from my Mac (An old intel one), indeed when building in the Rpi4 I change the argument to aarch64-unknown-linux-musl and rust part works smoothly.

Regarding node version, if I am not wrong, shouldn't it be using the one in the container?.

**Comment by euzu** [comment]
I dont know wjy you are getting this error, i dont have this. But i try to find out what the problem could be.

I have added scripts and a will release docker image  for aarch64 target.

**Comment by andresjocrack** [comment]
Thank you sooooo much!.
