### ISSUE TITLE
Can not get it to work

### ISSUE THREAD

**Issue by a1ad** [euzu/m3u-filter#31]
I don't get it... 
* compiled successful 
* created a config and source file
* moved the files to the docker dir
*  docker build... needed some more non mandatory files like mapping, api-proxy, so i created empty ones.
* docker build needed a web and web/static directory?? so created empty ones.
* Docker build ok
* Docker-compose up
```
m3u-filter    | [2023-12-29T14:03:16Z INFO  m3u_filter] Version: 1.1.4
m3u-filter    | [2023-12-29T14:03:16Z INFO  m3u_filter] Current time: 2023-12-29 15:03:16
m3u-filter    | [2023-12-29T14:03:16Z INFO  m3u_filter] Working dir: "/data"
m3u-filter    | [2023-12-29T14:03:16Z INFO  m3u_filter] Config file: ./config.yml
m3u-filter    | [2023-12-29T14:03:16Z ERROR m3u_filter::config_reader] cant read mapping file: missing field `mappings`
m3u-filter    | [2023-12-29T14:03:16Z INFO  m3u_filter::config_reader] Mappings File: /mapping.yml
m3u-filter    | [2023-12-29T14:03:16Z ERROR m3u_filter::config_reader] cant read api-proxy-config file: missing field `server`
m3u-filter    | [2023-12-29T14:03:16Z WARN  m3u_filter::config_reader] cant read api_proxy_config file: /api-proxy.yml
m3u-filter    | [2023-12-29T14:03:16Z INFO  m3u_filter] Web root: /web
m3u-filter    | [2023-12-29T14:03:16Z INFO  m3u_filter] Server running: http://0.0.0.0:8901
m3u-filter    | [2023-12-29T14:03:16Z INFO  actix_server::builder] starting 16 workers
m3u-filter    | [2023-12-29T14:03:16Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
```
Seems up, but when I go to the URL I got the error:
`No such file or directory (os error 2)`

So I guess the web dir can't be empty?

 What do I need to do to access the web??

**Comment by euzu** [comment]
Hi,
the docker file is for a complete  docker image generation including optional files.

You can edit the Dockerfile and remove mapping and api-proxy  configurations and web directory
However if you dont plan to run in server mode you can actually run in cli mode.
Empty optional config files are not allowed.
The web directory can be build in the frontend directory with npm or yarn. Or you can extract the web directory from one release.

**Comment by a1ad** [comment]
I am still learning how to use the tool. I was hoping to get it to work with docker and server mode (with web ui) so I can create a test env. A clear how to is lacking, but I get there eventually :-). Thanks for the response, I look in to it when I have some spare time.

**Comment by euzu** [comment]
@a1ad can i close this issue or dou you have further questions?

**Comment by a1ad** [comment]
Sorry, busy weeks. Didn't test it yet.

**Comment by euzu** [comment]
Closed due to inactivitiy.  Please use the discussion section for this kind of questions.
