### ISSUE TITLE
Publish official docker image

### ISSUE THREAD

**Issue by kingschnulli** [euzu/m3u-filter#34]
**Is your feature request related to a problem? Please describe.**
Currently no official docker image is available 

**Describe the solution you'd like**
Create a docker image with automatic generation through GitHub actions and push to docker hub

**Describe alternatives you've considered**
Dockerize myself, has to be redone for every release. Can not easily be reused over several machines

**Additional context**
Never done that, but should be doable

**Comment by euzu** [comment]
@kingschnulli the docker image contains the config files which are unique for everyone. I dont think it will make much sense to create a docker image on dockerhub.
 
I use a simple Dockerifile to create my docker image 

```docker
FROM gcr.io/distroless/base-debian12 as build


FROM scratch

WORKDIR /

COPY --from=build /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY ["./m3u-filter", "./config.yml", "source.yml", "./api-proxy.yml",  "./mapping.yml", "/"]
COPY ./web /web

CMD ["/m3u-filter", "-s", "-c", "/config.yml"]
```

Then i create the image with this dockerfile.
