### ISSUE TITLE
panel_api.php expectation not implemented

### ISSUE THREAD

**Issue by haroldthegray** [euzu/m3u-filter#37]
**Describe the bug**
Support for Xtreams expects a panel_api.php endpoint. It appears players/clients use this to check for information on the user.

**To Reproduce**
1. Add xtream credentials for m3u_filter to a client (GSE SMART IPTV in my case).
2. Observe the error on retrieving user information.
3. Observe the attempted URI in m3u-filter logs

**Expected behavior**
The same information for hitting player_api.php with credentials but without the **_action_** attribute (returning user info) should occur when hitting panel_api.php with credentials but without the **_action_** attribute.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I temporarily remediated with nginx reverse proxy config, but this does not fix the problem for other users.

```nginx
server {
    ...
    location / {
        ...
        rewrite ^/panel_api.php$ /player_api.php last;
        ...
    }
}
```

**Comment by euzu** [comment]
@haroldthegray i have added panel_api.php.
