### ISSUE TITLE
Xtream api endpoint get_live_streams doesn’t filter by category_id

### ISSUE THREAD

**Issue by RohirrimRider** [euzu/m3u-filter#39]
**Describe the bug**
All streams are returned from the get_live_streams endpoint even when category_id query parameter is passed

**To Reproduce**
1. Run xtream output with multiple groups
2. Query the api endpoint with action=get_live_streams&category_id=XX
3. All streams are returned with all categories

**Expected behavior**
I should only get the streams with the matching category ID

**Screenshots**

**Desktop (please complete the following information):**
 Docker

**Smartphone (please complete the following information):**

**Additional context**

**Comment by euzu** [comment]
@RohirrimRider this should be solved in master branch now

**Comment by RohirrimRider** [comment]
@euzu the issue seems resolved, but now I'm getting this when trying to stream: (username is hello, password is world). The 1416 is the stream channel id returned from get_live_streams.

```
m3u-filter  | [2024-03-26T18:22:37Z INFO  actix_web::middleware::logger] 127.0.0.1 "HEAD /live/hello/world/1416.ts HTTP/1.1" 405 0 "-" "-" 0.000161
m3u-filter  | [2024-03-26T18:22:37Z DEBUG m3u_filter::api::xtream_api] Cant figure out stream url for target pl1, context live, action 1416.ts
m3u-filter  | [2024-03-26T18:22:37Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /live/hello/world/1416.ts HTTP/1.1" 400 0 "-" "-" 0.000314
m3u-filter  | [2024-03-26T18:22:37Z DEBUG m3u_filter::api::xtream_api] Cant figure out stream url for target pl1, context live, action 1416.ts
m3u-filter  | [2024-03-26T18:22:37Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /live/hello/world/1416.ts HTTP/1.1" 400 0 "-" "libmpv" 0.000117
```

**Comment by euzu** [comment]
Is there a target name mismatch for the user?

**Comment by RohirrimRider** [comment]
@euzu I think it was a problem with using m3u source. I have moved to another source.

**Comment by RohirrimRider** [comment]
I confirmed master is working for the original issue
