### ISSUE TITLE
I think you broke api-proxy.yml

### ISSUE THREAD

**Issue by RohirrimRider** [euzu/m3u-filter#50]
I'm unable to add any new users to api-proxy.yml. I think this might be caused by the latest changes to allow env vars.

To recreate:

add user/password to api-proxy.yml. Restart. Try to use the login and you'll get a 401.

**Comment by euzu** [comment]
@RohirrimRider i tested it and it is working, i can get the playlist.  Is your yaml file invalid ? 
I made some changes to the code, can you pull master and test again.

**Comment by euzu** [comment]
Clsoing due to inactivity,  tested and working
