### ISSUE TITLE
Restrict access or suppress web access

### ISSUE THREAD

**Issue by lezioul** [euzu/m3u-filter#52]
Hi,

it would be a great thing to add credentials on /web or give the ability to disable the webapp without disabling the proxy.
I use m3u-filter on a vps and i have disallowed every public IPs except mine so webapp is not fully accessible.

Best Regards,

Lezioul

**Comment by euzu** [comment]
@lezioul  i have pushed the changes to the master branch, 

in `config.yml`

[web_ui_enabled](https://github.com/euzu/m3u-filter/wiki/config_web_ui_enabled)
[web_auth](https://github.com/euzu/m3u-filter/wiki/config_web_auth)

**Comment by euzu** [comment]
@lezioul  in order to use web_auth you need to build the backend and the frontend.
Inside the `bin` folder are some usefull scripts.

**Comment by lezioul** [comment]
Seems really nice! I'll try this tomorrow. 
By the way, how can i activate DEBUG level in logger,  is there an environment variable?

Best regards

**Comment by euzu** [comment]
LogLevel can only be set through program arguments.
I could not figure out howto change the log level for the env_logger crate after start.
There are other log crates which support dynamic log level changeing.  
But i dont think that this is necessary.


` -l, --log-level <LOG_LEVEL>      log level` 

```
Usage: m3u-filter [OPTIONS]

Options:
  -p, --config-path <CONFIG_PATH>  The config directory
  -c, --config <CONFIG_FILE>       The config file
  -i, --source <SOURCE_FILE>       The source config file
  -m, --mapping <MAPPING_FILE>     The mapping file
  -t, --target <TARGET>            The target to process
  -a, --api-proxy <API_PROXY>      The user file
  -s, --server                     Run in server mode
  -l, --log-level <LOG_LEVEL>      log level
  -h, --help                       Print help
  -V, --version                    Print version
  --genpwd                         Generate UI Password
```

**Comment by lezioul** [comment]
I was talking about a variable in docker-compose.yml file.

**Comment by euzu** [comment]
I have updated master branch.
`M3U_FILTER_LOG` env variable can be used to  to define the log level.

Cli-Argument -> if not available -> env var  `M3U_FILTER_LOG` -> if not availabel  `info`

**Comment by lezioul** [comment]
Sorry, i was not able to build the master, so i could not test.

**Comment by euzu** [comment]
@lezioul there is a new docker image release if you want to test, you can run it in docker.
