### ISSUE TITLE
Global `templates` and `tag` in `mapping.yml`

### ISSUE THREAD

**Issue by kumy** [euzu/m3u-filter#7]
**Is your feature request related to a problem? Please describe.**
When multiple mapping are defined, the `templates` and `tag` are a repeated on all mapping entries, leading to discrepancy when one needs an update.

**Describe the solution you'd like**
Aside having `templates` and `tags` defined in each mapping, It would be nice if the `templates` and `tags` could also have a global definition

**Describe alternatives you've considered**
I duplicated the patterns in each section...

**Additional context**
Some declarations:
https://github.com/euzu/m3u-filter/blob/9905dbff674055e10b664b2060a4d09142a56b2f/mapping.yml#L4-L40

https://github.com/euzu/m3u-filter/blob/9905dbff674055e10b664b2060a4d09142a56b2f/mapping.yml#L84-L117

...

**Comment by euzu** [comment]
Moved templates one level up and removed from mapper definitions. Templates are now global in mappings.yml. There is no need to define local templates

**Comment by euzu** [comment]
tags moved one level up, there is no local tag definition anymore.  only `tags`.
Tags can be used  in suffix and prefix  as <tag:tag_name>  where tag_name is the unique name in the tags definition,

**Comment by kumy** [comment]
Cool, thanks
