### ISSUE TITLE
Add support for EPG timeshift per target

### ISSUE THREAD

**Issue by blockloop** [euzu/m3u-filter#72]
**Is your feature request related to a problem? Please describe.**

The EPG I'm using is for a specific timezone, but the users are all in different timezones. 

**Describe the solution you'd like**
I'd like to set the EPG timeshift per target so that the EPG will be accurate.

**Describe alternatives you've considered**
None really. I could use a cloud service that provides this like [xtream-editor](https://www.xtream-editor.com/) but I'd rather not.

**Comment by euzu** [comment]
You would like to set the them difference where ? 
You mean for each user ?

**Comment by euzu** [comment]
what do you prefer for the format ?
* `-2:30, 1:45, +0:15`         <- i would go with this
* `+2h30m, -1h15m`

**Comment by blockloop** [comment]
either way works for me

**Comment by euzu** [comment]
@blockloop i have pushed a version to a new branch [feature/issue-72-epg_timeshift](https://github.com/euzu/m3u-filter/tree/feature/issue-72-epg_timeshift).

I could not test it. I will give you a feedback when i have tested it.

**Comment by euzu** [comment]
@blockloop did you test it ?

**Comment by euzu** [comment]
in latest release
