### ISSUE TITLE
Catchup support?

### ISSUE THREAD

**Issue by SanderM2** [euzu/m3u-filter#78]
It looks like catchup service privided by my xtreme provider is no longer working when I filter my channels through m3u-filter?

**Comment by euzu** [comment]
It could be that there is an api which m3u-filter does not support. Can you find out what url the clients are calling ?

**Comment by SanderM2** [comment]
Yes, it's calling /streaming/timeshift.php like this:

[2024-08-26T10:55:17Z INFO  actix_web::middleware::logger] 192.168.178.100 "GET /streaming/timeshift.php?username=user&password=pass&stream=3&start=2024-8-22:23-15&duration=60 HTTP/1.1" 404 0 "-" "gblECHvqadNfIX4dvRsO" 0.001018

**Comment by euzu** [comment]
@SanderM2 thank you, i need to look at the api implementation for catchup. I could need your help because i can only implement without testting it. Are you able to clone a git branch and build a binary?

**Comment by euzu** [comment]
> Yes, it's calling /streaming/timeshift.php like this:
> 
> [2024-08-26T10:55:17Z INFO actix_web::middleware::logger] 192.168.178.100 "GET /streaming/timeshift.php?username=user&password=pass&stream=3&start=2024-8-22:23-15&duration=60 HTTP/1.1" 404 0 "-" "gblECHvqadNfIX4dvRsO" 0.001018

Is this for xtream api or m3u ?

**Comment by SanderM2** [comment]
I can clonse a git and build. Haven't tried it for m3u-filter yet but should be no issue.

The url was for xtream api

**Comment by euzu** [comment]
Ok thanks, during implementation i will inform you. This week i am really very very busy with my work. I hope i can have time next week.

**Comment by SanderM2** [comment]
Ok. Thanks

**Comment by euzu** [comment]
@SanderM2 can you test  [feature/issue-78-catchup](https://github.com/euzu/m3u-filter/tree/feature/issue-78-catchup)

**Comment by SanderM2** [comment]
@euzu I just came back from a trip to France (for work) but it seems that the feature you wanted me to test is no longer available?

I'm getting:

404 - page not found
Cannot find a valid ref in feature/issue-78-catchup

**Comment by SanderM2** [comment]
Tested thoroughly and it works perfectly fine.
Thanks for the quick update!
