### ISSUE TITLE
Neasted template: reuse templates in templates

### ISSUE THREAD

**Issue by kumy** [euzu/m3u-filter#8]
**Is your feature request related to a problem? Please describe.**
Unnecessary repetitive patterns in mapping templates.

**Describe the solution you'd like**
The templates in `mapping.yml` is a cool feature, but to simplify some rules it would be nice if they can be:
1. Aliased
2. Reusable in next templates

Consider the 2 definitions: `delimiter` and `quality`
https://github.com/euzu/m3u-filter/blob/9905dbff674055e10b664b2060a4d09142a56b2f/mapping.yml#L94-L99

We can see that the second is repeating the `delimiter` pattern in it's own expression. That also applies for the other defined template entries.

**Describe alternatives you've considered**
1. Aliases: L96 and L117 are examples of aliases, but the yaml representation may be different, like `name` could be an array :shrug: 
2. Reusable: I've added comments with the natural syntax I would have naively used: L96 L99 L102...

**Additional context**
Problem is accentuated by #7

**Comment by euzu** [comment]
done.
