### ISSUE TITLE
Duplicate group name with different category_id

### ISSUE THREAD

**Issue by SanderM2** [euzu/m3u-filter#83]
Hello,

I have a mapping.yml file that changes the group of several channels to "General" for channels on two different IPTV provider.
Now I noticed that my IPTV app shows two groups with the same name: General.

Looking at the response of /player_api.php?username=xxxx&password=yyyy&action=get_live_categories'
I also see this:

`[{"category_id":"92","category_name":"General","parent_id":0},{"category_id":"93","category_name":"General","parent_id":0}]
`
Is this a bug? Or am I just missing some configuration?

my mapper for these channels all look the same like this:

```
    - filter: '!IS_IPTV_PROVIDER1! and Type = live'
      pattern: Name ~ "^!PROVIDER1_SEPARATOR!(UK)!PROVIDER1_SEPARATOR! Sky Nature$"
      attributes:
        group: General
        name: SKY Nature
        chno: 2001
      prefix:
        name: "\xB9 "
      assignments:
        title: name
```

**Comment by SanderM2** [comment]
After some more testing I noticed that sometimes the category_id becomes the same id but most of they time they are different.

**Comment by SanderM2** [comment]
I attempted to add a third input source (provider) and move channels from it into the General group. However, this resulted in the creation of three separate General groups, each with a different category_id.

It seems that m3u-filter creates new groups for channels based on their input source.

As a result, I'm unable to consolidate channels from different providers into a single new group. Instead, it always creates multiple groups with the same name.

**Comment by SanderM2** [comment]
Any ideas?

I’m stuck now. Can’t get this fixed so cannot continue with my mapping.yaml.

I wonder if there is a solution for this? Or is this the way it works?

If I cannot move channels from multiple providers in the same single group my whole idea/setup is becoming useles ;(

**Comment by euzu** [comment]
@SanderM2 i am working on it. I need some time to analyze the problem. What you describe should not happen. The Group names should be distinct over the same type.

**Comment by SanderM2** [comment]
Thanks euzu!

If you need more info or someone to test things, let me know. I hope you can find the cause soon. 

It’s actually the only thing now keeping me from using it. I’ll have to wait for you to get back on this.

thanks man!

**Comment by euzu** [comment]
@SanderM2 i have finally found the problem. It  occurs when you have multiple inputs with the same group name (what you have described).

I try to fix this problem.

**Comment by euzu** [comment]
@SanderM2 i have pushed  to [feature/multi_input_groups](https://github.com/euzu/m3u-filter/tree/feature/multi_input_groups).

I could not test it, it compiles, but i dont know if it runs. I will continue tomorrow when i have time. 

If you have time, you could test it.

**Comment by SanderM2** [comment]
I have just compiled the multi_input_groups version and tried running my configuration but it failed to start with the following error:

```
[2024-09-11T06:59:50Z INFO  m3u_filter] Log Level INFO
[2024-09-11T06:59:50Z INFO  m3u_filter] Version: 2.0.3
[2024-09-11T06:59:50Z INFO  m3u_filter] Current time: 2024-09-11 08:59:50
[2024-09-11T06:59:50Z INFO  m3u_filter] Working dir: "/data"
[2024-09-11T06:59:50Z INFO  m3u_filter] Config dir: "/config"
[2024-09-11T06:59:50Z INFO  m3u_filter] Config file: /config/config.yml
[2024-09-11T06:59:50Z INFO  m3u_filter] Source file: /config/source.yml
[2024-09-11T06:59:51Z INFO  m3u_filter::utils::config_reader] Mappings File: /config/mapping.yml
[2024-09-11T06:59:51Z INFO  m3u_filter::utils::config_reader] Api Proxy File: /config/api-proxy.yml
[2024-09-11T06:59:51Z INFO  m3u_filter] Server running: http://0.0.0.0:8000
[2024-09-11T06:59:51Z INFO  m3u_filter::api::main_api] Web root: "/web"
[2024-09-11T06:59:51Z INFO  actix_server::builder] starting 1 workers
[2024-09-11T06:59:51Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2024-09-11T06:59:51Z INFO  actix_server::server] starting service: "actix-web-service-0.0.0.0:8000", workers: 1, listening on: 0.0.0.0:8000
[2024-09-11T06:59:58Z INFO  actix_server::server] SIGTERM received; starting graceful shutdown
[2024-09-11T06:59:58Z INFO  actix_server::accept] accept thread stopped
[2024-09-11T07:00:07Z INFO  m3u_filter] Log Level INFO
[2024-09-11T07:00:07Z INFO  m3u_filter] Version: 2.0.3
[2024-09-11T07:00:07Z INFO  m3u_filter] Current time: 2024-09-11 09:00:07
[2024-09-11T07:00:07Z INFO  m3u_filter] Working dir: "/data"
[2024-09-11T07:00:07Z INFO  m3u_filter] Config dir: "/config"
[2024-09-11T07:00:07Z INFO  m3u_filter] Config file: /config/config.yml
[2024-09-11T07:00:07Z INFO  m3u_filter] Source file: /config/source.yml
[2024-09-11T07:00:07Z INFO  m3u_filter::utils::config_reader] Mappings File: /config/mapping.yml
[2024-09-11T07:00:07Z INFO  m3u_filter::utils::config_reader] Api Proxy File: /config/api-proxy.yml
[2024-09-11T07:00:07Z INFO  m3u_filter] Server running: http://0.0.0.0:8000
[2024-09-11T07:00:07Z INFO  m3u_filter::api::main_api] Web root: "/web"
[2024-09-11T07:00:07Z INFO  actix_server::builder] starting 1 workers
[2024-09-11T07:00:07Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2024-09-11T07:00:07Z INFO  actix_server::server] starting service: "actix-web-service-0.0.0.0:8000", workers: 1, listening on: 0.0.0.0:8000
thread 'main' panicked at src/processing/playlist_processor.rs:400:62:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ff94cbb7f34 - <unknown>
   1:     0x7ff94c9d561b - <unknown>
   2:     0x7ff94cb9105e - <unknown>
   3:     0x7ff94cbbcb49 - <unknown>
   4:     0x7ff94cbbc43b - <unknown>
   5:     0x7ff94cbbd65e - <unknown>
   6:     0x7ff94cbbce8a - <unknown>
   7:     0x7ff94cbbce19 - <unknown>
   8:     0x7ff94cbbce06 - <unknown>
   9:     0x7ff94c8292f2 - <unknown>
  10:     0x7ff94c82948b - <unknown>
  11:     0x7ff94c829898 - <unknown>
  12:     0x7ff94c8893b4 - <unknown>
  13:     0x7ff94c911b90 - <unknown>
  14:     0x7ff94c90e8a1 - <unknown>
  15:     0x7ff94c91b69d - <unknown>
  16:     0x7ff94c893a16 - <unknown>
  17:     0x7ff94cbc2ee8 - <unknown>
  18:     0x7ff94c892c64 - <unknown>
  19:     0x7ff94c93199f - <unknown>
  20:     0x7ff94c873961 - <unknown>
  21:     0x7ff94c93dd64 - <unknown>

```

I think this error comes up right after downloading the categories/streams from the providers.

**Comment by euzu** [comment]
@SanderM2 i dont know why this happens, i think i need to debug to understand it.

**Comment by SanderM2** [comment]
I reverted back to the previous version and now it doesn't crash so it must be something with the latest changes.
If you want me to test something, I can do so, just ask.

**Comment by euzu** [comment]
@SanderM2 can you test again please, i have pushed some changes to the branch  [feature/multi_input_groups](https://github.com/euzu/m3u-filter/tree/feature/multi_input_groups)

**Comment by SanderM2** [comment]
I just tested it, and it seems to be working perfectly now! There are no more duplicate groups. Thank you for your prompt efforts in resolving this!

**Comment by euzu** [comment]
You are welcome,  you can close this issue if you like.

**Comment by SanderM2** [comment]
I have this in my templates: (auto generated)

```
- name: PROVIDER_1_VOD
  value: '!IS_PROVIDER_1! AND (((Type = vod) OR (Type = series)) AND ( Group ~ ".*" ))'
```

For some reason it is importing all movies but no series at all...
Could it be that there is an issue with Type=series still?

**Comment by euzu** [comment]
@SanderM2 you can simplify `(((Type = vod) OR (Type = series)) ...`  as `((Type = vod OR Type = series) ...` 

What is your input source ?  m3u sources do not support  type, it is guessed based on stream url ending ans series are not supported.

If your source is xtream  then series are supported. If this not works, then i need to debug to understand the problem.

**Comment by SanderM2** [comment]
I am using xtream as an input source so it should be able to find these series.
I'm not sure why it is not working. I have double checked my configuration multiple times but cannot find an errors.

I think it's a bug?

**Comment by euzu** [comment]
you are sure you did not set `xtream_skip_series: true` ?

**Comment by SanderM2** [comment]
Still looking into this myself too. I now have a base config file like this:

```
templates:
- name: IS_PROVIDER_1
  value: Url ~ "http://some\.domain\.com:1234"
- name: PROVIDER_1_VOD
  value: '!IS_PROVIDER_1! AND (((Type = vod) OR (Type = series)))'
sources:
- inputs:
  - name: provider1
    enabled: true
    type: xtream
    ... rest of the xtream details removed ...
  targets:
  - name: all_mapped_channels
    filename: playlist_all_mapped_channels
    output:
    - type: xtream
    filter: (!PROVIDER_1_VOD!) 
    options:
      ignore_logo: true
      xtream_skip_live_direct_source: true
      xtream_skip_video_direct_source: true
      xtream_skip_series_direct_source: true
    sort:
      groups:
        order: asc
```


This is not working. Movies are passed but no series.

**Comment by SanderM2** [comment]
I have found that even a simple filter for a target configured like this will return no results:

```
  targets:
  - name: all_mapped_channels
    filename: playlist_all_mapped_channels
    output:
    - type: xtream
    filter: 'Type = series'
    options:
      ignore_logo: true
      xtream_skip_live_direct_source: true
      xtream_skip_video_direct_source: true
      xtream_skip_series_direct_source: true
    sort:
      groups:
        order: asc
```

If I change the filter to Type = vod in the above example it is passing all movies.
And I change it to !IS_PROVIDER_1! it is passing all live, movies and series.

It looks like an issue with the Type = series comparison?
