### ISSUE TITLE
Update filtered m3u even when download fails

### ISSUE THREAD

**Issue by lasharor** [euzu/m3u-filter#92]
**Is your feature request related to a problem? Please describe.**
My source will not allow me to download the M3U file multiple times per day. So when I try to work on the filtering it makes the process cumbersome as the resulting m3u from m3u-filter will not update due to failing download of the source. 

ERROR m3u_filter::processing::playlist_processor] Source at 0 is empty

**Describe the solution you'd like**
Please, even if download failes update the resulting m3u file based on the filters defined in source.yml

**Comment by euzu** [comment]
@lasharor it is very simple.  Save the m3u playlist   as file  for example playlist.m3u  on your harddisk.
Then use a simple http server , you can simply search on github there are a lot, i am using  python server like 

`python3 -m http.server 7000 --directory ./web-root/`. 
 
Then use the input url   like :  `url: http://localhost:7000/playlist.m3u`

When you finish your configuration you can point the url to your provider.

**Comment by euzu** [comment]
@lasharor i forgot that input url supports  file paths.  you can simply  write
`url: /home/lasharor/my_playlist.m3u`

You dont need a http server.

Is it solved for you now ?

**Comment by lasharor** [comment]
thank you, I suppose the local path will do the trick.
