### ISSUE TITLE
panic on parsing xmltv file

### ISSUE THREAD

**Issue by rgrente** [euzu/m3u-filter#95]
**Describe the bug**
I am getting an error when configure an xmltv file. The xmltv_parser seems to be the source of the error.

**To Reproduce**
Define an EPG URL in config file
Run m3u_filter

**Expected behavior**
Here is the logs (DEBUG + RUST_BACKTRACE=full)

`
[2024-10-07T11:56:45Z DEBUG m3u_filter::utils::request_utils] getting input text content working_dir: /root/m3u-filter_v2.0.4_linux_x86_64/data, url: xmltv_tnt.xml
thread 'main' panicked at src/processing/xmltv_parser.rs:60:38:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7fef5b2e9fc4 - <unknown>
   1:     0x7fef5b101c3b - <unknown>
   2:     0x7fef5b2bf27e - <unknown>
   3:     0x7fef5b2ee49e - <unknown>
   4:     0x7fef5b2ef508 - <unknown>
   5:     0x7fef5b2eee12 - <unknown>
   6:     0x7fef5b2eeda9 - <unknown>
   7:     0x7fef5b2eed94 - <unknown>
   8:     0x7fef5af49b72 - <unknown>
   9:     0x7fef5af49d0b - <unknown>
  10:     0x7fef5af4a118 - <unknown>
  11:     0x7fef5b03e8d6 - <unknown>
  12:     0x7fef5b04386d - <unknown>
  13:     0x7fef5afbaa91 - <unknown>
  14:     0x7fef5b2f516b - <unknown>
  15:     0x7fef5afb77cb - <unknown>
  16:     0x7fef5b059d86 - <unknown>
  17:     0x7fef5af963f8 - <unknown>
  18:     0x7fef5b066a5b - <unknown>
Aborted
`

**Additional context**
Running m3u-filter on LXC host on Debian 11
Here is the URL of the XMLTV file : https://xmltvfr.fr/xmltv/xmltv_tnt.xml
Trying with other sources do the same.

Thx

**Comment by euzu** [comment]
@rgrente i have fixed this on the master branch. Can you build the binary or should i build one for you ?

**Comment by rgrente** [comment]
if you can build one that's cool ! :)

**Comment by euzu** [comment]
@rgrente what OS ? linux or windows ?

**Comment by euzu** [comment]
Linux static binary:
[m3u-filter.zip](https://github.com/user-attachments/files/17278741/m3u-filter.zip)

**Comment by rgrente** [comment]
seems to be ok. Thx for your (quick) response
