### ISSUE TITLE
thread 'actix-rt|system:0|arbiter:0' panicked at src/processing/xmltv_parser.rs:60:38:

### ISSUE THREAD

**Issue by Metathesus** [euzu/m3u-filter#96]
Hello,
Processing stop and no target generated

Logs:
thread 'actix-rt|system:0|arbiter:0' panicked at src/processing/xmltv_parser.rs:60:38:

Using docker latest image (v2.04) but this wasn't occurs with prevoius image (v2.03)

source.yml:
sources:
  - input:
       - epg_url: 'https://epgshare01.online/epgshare01/epg_ripper_FR1.xml.gz'

Removing the epg_url part permit to continue...

**Comment by euzu** [comment]
@Metathesus this seems a problem with the xml file paraing. I fixed an error 5 days ago. If you can build the binary you can test if this fixes your problem.

**Comment by Metathesus** [comment]
Thanks for the fix, I'm using docker, and to be honest, I'm not able to build binary...

**Comment by euzu** [comment]
@Metathesus  here is a link to a compiled binary
[m3u-filter.zip](https://github.com/user-attachments/files/17278741/m3u-filter.zip)

you can mount into the docker container.

**Comment by Metathesus** [comment]
Thank you!
After mounting in docker like ` - /mnt/Docker/m3u_filter/binaries/m3u-filter: /m3u-filter` everythinh is OK

**Comment by blockloop** [comment]
Has this been merged @Metathesus ?

**Comment by euzu** [comment]
@blockloop yes this should be fixed with the latest release.
