### ISSUE TITLE
Pre built alpine container image for m3u filter 

### ISSUE THREAD

**Issue by adamsdavis572** [euzu/m3u-filter#99]
**Is your feature request related to a problem? Please describe.**
Would be useful to get a container image of m3u-filter that has a shell so that I can 1) debug issues by running a shell in the container and 2) create more sophisticated healthchecks using curl etc. 

Currently the healthcheck endpoint doesn't determine if the container it's experiencing network connectivity issues. 

**Describe the solution you'd like**
A release that includes a container that has a full shell

**Comment by euzu** [comment]
@adamsdavis572  is the alpine  base enough ? i have installed bash and curl .

 ```
# Alpine Final container
FROM alpine:latest as alpine-final

RUN apk add --no-cache bash curl

WORKDIR /app

COPY ./m3u-filter .
COPY ./web ./web
# config should be mounted as volume
# COPY ./config ./config

ENTRYPOINT ["/app/m3u-filter"]
CMD ["-s", "-p", "/app/config"]
```

The difference is the application path:
The config should be changed to match the new path.


the simplest docker-compose could look like
```docker
services:
  m3u-filter:
    container_name: m3u-filter
    image: ghcr.io/euzu/m3u-filter-alpine:latest
    working_dir: /
    volumes:
      - /home/m3u-filter/data:/app/data
      - /home/m3u-filter/config:/app/config
      - /home/m3u-filter/backup:/app/backup
      - /home/m3u-filter/downloads:/app/downloads
    environment:
      - TZ=Europe/Paris
    ports:
      - "8901:8901"
    restart: unless-stopped
```

if it is ok i can create a new image.

**Comment by euzu** [comment]
@adamsdavis572  i have deployed a new image

[m3u-filter-alpine](https://github.com/euzu/m3u-filter/pkgs/container/m3u-filter-alpine)

**Comment by adamsdavis572** [comment]
@euzu that is perfect, thank you. I'll try it out and report back

**Comment by adamsdavis572** [comment]
Thats working great - thanks very much @euzu
